// Contract ABIs - These will be generated by Hardhat after compilation
// Located in artifacts/contracts/

// Simplified ABIs for frontend use
// Full ABIs can be imported from artifacts after compilation

export const MyTokenABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function getTotalSupply() view returns (uint256)",
  "function getBalance(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function owner() view returns (address)",
];

export const MyNFTABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function ownerOf(uint256) view returns (address)",
  "function tokenURI(uint256) view returns (string)",
  "function getOwner(uint256) view returns (address)",
  "function getTokenURI(uint256) view returns (string)",
  "function mint(address to, string memory tokenURI) returns (uint256)",
  "function owner() view returns (address)",
];

export const MyMultiTokenABI = [
  "function GOLD() view returns (uint256)",
  "function SILVER() view returns (uint256)",
  "function BRONZE() view returns (uint256)",
  "function balanceOf(address, uint256) view returns (uint256)",
  "function getBalance(address, uint256) view returns (uint256)",
  "function getTotalSupply(uint256) pure returns (uint256)",
  "function mint(address to, uint256 id, uint256 amount, bytes memory data)",
  "function mintBatch(address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data)",
  "function owner() view returns (address)",
  "function uri(uint256) view returns (string)",
];

export const SecureVaultABI = [
  "function deposit() payable",
  "function withdraw(uint256 amount)",
  "function emergencyWithdraw()",
  "function pause()",
  "function unpause()",
  "function deposits(address) view returns (uint256)",
  "function totalDeposits() view returns (uint256)",
  "function getBalance(address user) view returns (uint256)",
  "function getContractBalance() view returns (uint256)",
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
];

